# Use audio as master (prevents drift in long videos)
video-sync=audio

# Disable resampling tricks
interpolation=no

# Keep pitch normal
audio-pitch-correction=yes

# Force stable samplerate
audio-samplerate=48000
audio-channels=stereo

# Hardware video decoding
hwdec=vaapi

# Reduce processing for smoother playback
profile=fast

# Repeat playlist forever
loop-playlist=inf

# Prefer English audio and subtitles
alang=eng
slang=eng
